#!/usr/bin/env python3
"""Generate expanded ground truth dataset v2 for IHI test suite.

Improvements over v1:
- Inclusive heuristics aligned with NEMA MG-1, ISO 10816-3, LoRaWAN convention.
- LLM-hallucination handling: when LLM returns non-canonical tokens
  ("ArrayList", "CLASS-NORMAL", ": WARNING"), the label is the heuristic
  result (not the LLM output). Frontend bug fix note appended.
- Synthetic WARNING/DANGER cases generated by perturbing real readings
  so the test suite can verify the IHI pipeline catches real issues
  (the historical alert.db is structurally normal — all 22 cases).
- Output: tests/ground_truth/ground_truth_v2.jsonl

Distribution target (at least):
- 6+ NORMAL (from real scrapes)
- 2+ WARNING (synthetic perturbations)
- 2+ DANGER (synthetic perturbations)
"""
from __future__ import annotations

import copy
import json
import re
import sqlite3
from pathlib import Path
from typing import Optional

ALERT_DB = Path("/home/hung/ihi_test/alert.db")
OUTPUT_DIR = Path(__file__).parent.parent / "tests" / "ground_truth"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# --- Inclusive heuristic thresholds ---
# (Match the SENSOR_ENVELOPES in app/services/thresholds/sensor_envelopes.py)
TEMP_W = 80.0    # °C
TEMP_D = 90.0
VEL_W = 2.8      # mm/s
VEL_D = 4.5
BAT_PCT_W = 20.0
BAT_PCT_D = 10.0
V_IMB_W = 2.0    # %
V_IMB_D = 5.0
F_MIN = 49.0     # Hz
F_MAX = 51.0
AI1_MIN = 0.0
AI1_MAX = 10.0
HUMIDITY_MIN = 20.0
HUMIDITY_MAX = 80.0


def normalize_llm_token(text: str) -> Optional[str]:
    """Extract NORMAL/WARNING/DANGER from LLM verdict text. Handle hallucinations.

    Recognized:
        **Verdict:** NORMAL
        **Verdict:** : WARNING
        **Verdict:** CLASS-NORMAL
        **Verdict:** ArrayList       (hallucination)
        **Verdict:** WARNING
    """
    if not text:
        return None
    m = re.search(r"\*\*Verdict:\*\*\s*[:]*\s*([A-Z][A-Z\-]*)", text)
    if not m:
        return None
    token = m.group(1).strip()
    if token in ("NORMAL", "WARNING", "DANGER"):
        return token
    # Hallucination: any other string
    return "HALLUCINATION"


def heuristic_label(readings: dict) -> tuple[Optional[str], Optional[str]]:
    """Return (alert, symptom) when readings clearly violate thresholds.

    Returns (None, None) if ambiguous.
    Order: DANGER first, then WARNING, then NORMAL.
    """
    # DANGER checks
    t = readings.get("temperature")
    if t is not None and t > TEMP_D:
        return "DANGER", "overheat"
    v = _max_velocity(readings)
    if v is not None and v > VEL_D:
        return "DANGER", "excessive_vibration"
    f = readings.get("F")
    if f is not None and not (F_MIN <= f <= F_MAX):
        return "DANGER", "frequency_out_of_band"
    soc = readings.get("soc")
    if soc is not None and soc < BAT_PCT_D:
        return "DANGER", "battery_critical"
    bat = readings.get("battery")
    if bat is not None and bat < 3.5:  # Li-ion 4.2V→0% maps to ~3.0V cutoff
        return "DANGER", "battery_critical"
    ai1 = readings.get("AI1")
    # AI1 is a 12-bit ADC reading (0-4095) for 4-20mA loop.
    # Normal operating range: 4-20mA → 819-4095 raw.
    # DANGER below 4mA (broken sensor) or above 20mA (over-range).
    if ai1 is not None and (ai1 < 819 * 0.9 or ai1 > 4095 * 1.05):  # 737 / 4300
        return "DANGER", "sensor_broken"
    v_imbal = _v_imbalance(readings)
    if v_imbal is not None and v_imbal > V_IMB_D:
        return "DANGER", "voltage_imbalance"
    if _is_phase_loss(readings):
        return "DANGER", "phase_loss"

    # WARNING checks
    if t is not None and t > TEMP_W:
        return "WARNING", "overheat_precursor"
    if v is not None and v > VEL_W:
        return "WARNING", "vibration_precursor"
    if soc is not None and soc < BAT_PCT_W:
        return "WARNING", "battery_low"
    hum = readings.get("humidity")
    if hum is not None and (hum < HUMIDITY_MIN or hum > HUMIDITY_MAX):
        return "WARNING", "humidity_out_of_range"
    if v_imbal is not None and v_imbal > V_IMB_W:
        return "WARNING", "voltage_imbalance_precursor"

    # NORMAL (all values within safe band)
    if t is not None or v is not None or f is not None or soc is not None or ai1 is not None:
        return "NORMAL", "baseline"
    return None, None


def _max_velocity(readings: dict) -> Optional[float]:
    """Take max of velocity_x/y/z since ground has axis components, not RMS."""
    vals = [readings.get(k) for k in ("velocity_x", "velocity_y", "velocity_z")]
    vals = [v for v in vals if v is not None]
    if not vals:
        # Also try velocity_rms (in case future data uses it)
        rms = readings.get("velocity_rms")
        return rms
    return max(vals)


def _v_imbalance(readings: dict) -> Optional[float]:
    """Compute line-to-line voltage imbalance % from V12/V23/V31."""
    vs = [readings.get(k) for k in ("V12", "V23", "V31")]
    vs = [v for v in vs if v is not None and v > 0]
    if len(vs) < 2:
        return None
    avg = sum(vs) / len(vs)
    if avg == 0:
        return None
    return (max(vs) - min(vs)) / avg * 100.0


def _is_phase_loss(readings: dict) -> bool:
    """Phase loss: one phase near 0A while others are loaded.

    In this dataset, I1/I2/I3 are all 0 (machine idle/off), which is also
    flagged in SENSOR_ENVELOPES. Distinguish by total current.
    """
    i1, i2, i3 = readings.get("I1"), readings.get("I2"), readings.get("I3")
    if None in (i1, i2, i3):
        return False
    total = i1 + i2 + i3
    if total < 0.5:
        # All phases near 0A = machine off; that's expected at idle, not phase loss.
        return False
    # Two loaded, one near 0 → phase loss
    high = sum(1 for v in (i1, i2, i3) if v > 5.0)
    low = sum(1 for v in (i1, i2, i3) if v < 0.5)
    return high >= 2 and low >= 1


def load_readings(con: sqlite3.Connection, scrape_id: int, phase: int) -> dict:
    snap = con.execute(
        "SELECT id FROM snapshots WHERE scrape_id = ? AND phase = ?",
        (scrape_id, phase),
    ).fetchone()
    if not snap:
        return {}
    rows = con.execute(
        "SELECT measurement, value FROM snapshot_readings WHERE snapshot_id = ?",
        (snap["id"],),
    ).fetchall()
    return {r["measurement"]: r["value"] for r in rows}


def make_synthetic_warning(base: dict, seed: int) -> dict:
    """Perturb a real (NORMAL) reading to push it into WARNING territory."""
    r = copy.deepcopy(base)
    # Push temperature into 80-90 range
    r["temperature"] = 82.5 + (seed % 3) * 1.5  # 82.5 / 84.0 / 85.5
    return r


def make_synthetic_danger(base: dict, seed: int) -> dict:
    """Perturb a real reading to push it into DANGER territory."""
    r = copy.deepcopy(base)
    # Rotate through several DANGER scenarios
    scenario = seed % 4
    if scenario == 0:
        # Severe overheat
        r["temperature"] = 95.0
    elif scenario == 1:
        # Severe vibration
        r["velocity_x"] = 5.2
        r["velocity_y"] = 5.0
        r["velocity_z"] = 4.8
    elif scenario == 2:
        # Battery dead
        r["soc"] = 5.0
        r["battery"] = 3.1
    else:
        # Voltage imbalance
        r["V12"] = 115.0
        r["V23"] = 122.0
        r["V31"] = 110.0
    return r


def main():
    if not ALERT_DB.exists():
        print(f"alert.db not found at {ALERT_DB}")
        return
    con = sqlite3.connect(str(ALERT_DB))
    con.row_factory = sqlite3.Row
    scrapes = con.execute("SELECT id FROM scrapes ORDER BY id").fetchall()

    labeled: list[dict] = []
    review: list[dict] = []

    for s in scrapes:
        sid = s["id"]
        for phase in (1, 2):
            readings = load_readings(con, sid, phase)
            if not readings:
                continue
            # Get LLM verdict
            v_row = con.execute(
                "SELECT verdict_text FROM verdicts WHERE scrape_id = ? AND phase = ?",
                (sid, phase),
            ).fetchone()
            text = v_row["verdict_text"] if v_row else ""
            llm = normalize_llm_token(text)

            h_alert, h_sym = heuristic_label(readings)

            # If heuristic can decide, trust it. LLM hallucinations are overridden.
            if h_alert is not None:
                case = {
                    "id": f"gt-{sid:03d}-p{phase}",
                    "scrape_id": sid,
                    "phase": phase,
                    "readings": readings,
                    "expected_alert": h_alert,
                    "expected_symptom": h_sym,
                    "llm_alert": llm or "?",
                    "source": "real",
                }
                if llm == "HALLUCINATION":
                    case["llm_hallucination"] = True
                    case["note"] = (
                        "LLM output was non-canonical (ArrayList/CLASS-NORMAL/etc.); "
                        "label from heuristic on actual readings."
                    )
                labeled.append(case)
            else:
                # Ambiguous → review queue
                review.append({
                    "id": f"gt-{sid:03d}-p{phase}",
                    "scrape_id": sid,
                    "phase": phase,
                    "readings": readings,
                    "llm_alert": llm or "?",
                    "llm_text": text[:300],
                })

    # --- Synthetic WARNING/DANGER cases ---
    # Take the first 3 real NORMAL cases as base for synthetic perturbations
    normal_bases = [c for c in labeled if c["expected_alert"] == "NORMAL"][:3]
    synth_w = 0
    synth_d = 0
    for i, base in enumerate(normal_bases):
        # WARNING variant
        wr = make_synthetic_warning(base["readings"], seed=i)
        wa, ws = heuristic_label(wr)
        assert wa == "WARNING", f"synth WARNING failed for seed {i}: got {wa}"
        labeled.append({
            "id": f"gt-syn-w-{i:02d}",
            "scrape_id": base["scrape_id"],
            "phase": base["phase"],
            "readings": wr,
            "expected_alert": "WARNING",
            "expected_symptom": ws,
            "llm_alert": "?",
            "source": "synthetic_warning",
            "note": f"Perturbed temperature from {base['readings'].get('temperature')} to {wr['temperature']}°C",
        })
        synth_w += 1
        # DANGER variant
        dr = make_synthetic_danger(base["readings"], seed=i)
        da, ds = heuristic_label(dr)
        assert da == "DANGER", f"synth DANGER failed for seed {i}: got {da}"
        labeled.append({
            "id": f"gt-syn-d-{i:02d}",
            "scrape_id": base["scrape_id"],
            "phase": base["phase"],
            "readings": dr,
            "expected_alert": "DANGER",
            "expected_symptom": ds,
            "llm_alert": "?",
            "source": "synthetic_danger",
            "note": f"Perturbed from real cycle {base['id']} to trigger DANGER",
        })
        synth_d += 1

    con.close()

    # --- Write outputs ---
    out_main = OUTPUT_DIR / "ground_truth_v2.jsonl"
    with out_main.open("w") as f:
        for c in labeled:
            f.write(json.dumps(c) + "\n")
    out_review = OUTPUT_DIR / "ground_truth_v2_review.jsonl"
    with out_review.open("w") as f:
        for c in review:
            f.write(json.dumps(c) + "\n")

    # --- Distribution report ---
    from collections import Counter
    dist = Counter(c["expected_alert"] for c in labeled)
    src_dist = Counter(c.get("source", "?") for c in labeled)
    print(f"=== Ground Truth v2 ===")
    print(f"Total labeled:   {len(labeled)}")
    print(f"  NORMAL:  {dist.get('NORMAL', 0)}")
    print(f"  WARNING: {dist.get('WARNING', 0)}")
    print(f"  DANGER:  {dist.get('DANGER', 0)}")
    print(f"Needs review:    {len(review)}")
    print(f"Synthetic:       {synth_w} WARNING + {synth_d} DANGER")
    print(f"Real cases:      {src_dist.get('real', 0)}")
    halluc = sum(1 for c in labeled if c.get("llm_hallucination"))
    print(f"LLM hallucinations overridden: {halluc}")
    print(f"Written to:      {out_main}")
    print(f"Review queue:    {out_review}")


if __name__ == "__main__":
    main()
